### ISSUE TITLE
Defect: Unexpected preconfig created when calling modify_preconfig method

### ISSUE THREAD

**Issue by janchan-hk** [aruba/pyedgeconnect#13]
## Description

There are significant changes on REST APIs in Orchestrator version 9.3. 

In pre-9.3 version of Orchestrator, the API for creating a new preconfig and API for updating an existing preconfig both use POST method but with different API Path. 

Starting from version 9.3, both APIs use exactly the same API path, but use POST method for preconfig creation, while PUT method for preconfig modification. 

In pyedgeconnect release 0.16.0-a1, when calling the modify_preconfig method on an Orchestrator with version 9.3, the specific preconfig would not be modified. Instead, a new preconfig with same name and new content would be unexpectedly created.  

## How to reproduce

When using this method to an Orchestrator with version 9.3 or above:

pyedgeconnect release: 0.16.0-a1

```python
from pyedgeconnect import Orchestrator

url = "<IP address or URL to an Orchestrator with 9.3 or above>"
api-key = "<API Key for non-user-based authentication>"
preconfig_id = "<Numeric ID of preconfig to apply>"
yaml_preconfig = "<YAML text of preconfig>"

orch = Orchestrator(url, api-key)
result = orch.modify_preconfig("preconfig_name", yaml_preconfig, True, preconfig_id)
```

## Expected behavior:

The method should return a boolean value. On the Orchestrator, the content of the preconfig with the ID specified is expected to be updated with the YAML content provided. 

## What could be the root cause:

Since Orchestrator 9.3, the API for updating preconfiguration given by preconfigId has been changed to PUT method instead of POST. However, in release 0.16.0-a1, the method is still using POST for both pre-9.3 and post-9.3 version of Orchestrator. 

The following is part of the code for the logic defined in the method modify_preconfig in the release 0.16.0-a1:

```python
if self.orch_version >= 9.3:
   path = f"/gms/appliance/preconfiguration?preconfigId={preconfig_id}"
else:
    path = f"/gms/appliance/preconfiguration/{preconfig_id}"

return self._post(
    path,
    data=data,
    return_type="bool",
)
```

Suggest to be modified to:

```python
if self.orch_version >= 9.3:
    return self._put(
        f"/gms/appliance/preconfiguration?preconfigId={preconfig_id}",
        data=data,
        return_type="bool",
    )
else:
    return self._post(
         f"/gms/appliance/preconfiguration/{preconfig_id}",
         data=data,
         return_type="bool",
    )
```

**Comment by adamwilkins-hpe** [comment]
@janchan-hk your changes were merged in the dev branch. Thanks for the support!
