### ISSUE TITLE
Bug on pyedgeconnect/orch /_bgp.py

### ISSUE THREAD

**Issue by thejptnaz** [aruba/pyedgeconnect#6]
#5 

def get_appliance_bgp_state_all_vrfs(
    self,
    ne_id: str,
) -> dict:
    """Returns appliance BGP current state

    .. list-table::
        :header-rows: 1

        * - Swagger Section
          - Method
          - Endpoint
        * - bgp
          - GET
          - /bgp/state/allVrfs/{neId}

    :param ne_id: Network Primary Key (nePk) of existing appliance,
        e.g. ``3.NE``
    :type ne_id: str
    :return: Returns appliance BGP state
    :rtype: dict
    """
    return self._get("/bgp/allVrfs/state/{}".format(ne_id)) #Change to return self._get("/bgp/state/allVrfs/{}".format(ne_id))

**Comment by zachcamara-hpe** [comment]
Resolved as part of 0.16.0 release
