### ISSUE TITLE
Add Support on health [Appliance health summary]

### ISSUE THREAD

**Issue by thejptnaz** [aruba/pyedgeconnect#7]
POST
/health
Returns health summary of all appliances

GET
/health/alarmPeriodSummary
Returns summary of alarms for a given appliance for that time period

GET
/health/healthThresholdConfig
Returns health threshold config

POST
/health/healthThresholdConfig
Update health threshold configuration

GET
/health/jitterPeriodSummary
Returns summary of jitter for a given appliance for that time period

GET
/health/latencyPeriodSummary
Returns summary of latency for a given appliance for that time period

GET
/health/lossPeriodSummary
Returns summary of loss for a given appliance for that time period

GET
/health/mosPeriodSummary
Returns summary of mos for a given appliance for that time period

**Comment by zachcamara-hpe** [comment]
This has been added in the 0.16.0 release
